export const discountProductList = [
  {
    id: "01",
    productName: "Stone and Beam Westview",
    imgUrl: require('../images/double-sofa-02.png'),
    category: "sofa",
    price: 193,
    discount: 30,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.5,
  },
  {
    id: "02",
    productName: "Rivet Bigelow Modern",
    imgUrl: require('../images/double-sofa-01.png'),
    category: "sofa",
    price: 253,
    discount: 20,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.7,
  },
  {
    id: "08",
    productName: "Baltsar Chair",
    imgUrl: require('../images/double-sofa-03.png'),
    category: "chair",
    price: 89,
    discount: 15,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.7,
  },
  {
    id: "09",
    productName: "Helmar Chair",
    imgUrl: require('../images/arm-chair-02.jpg'),
    category: "chair",
    price: 112,
    discount: 35,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.7,
  },
  {
    id: "12",
    productName: "Realme 8",
    imgUrl: require('../images/counter-timer-img - Copy (2).png'),
    category: "mobile",
    price: 599,
    discount: 10,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.8,
  },
  {
    id: "13",
    productName: "One Plus Nord",
    imgUrl: require('../images/arm-chair-03.jpg'),
    category: "mobile",
    price: 799,
    discount: 5,
    shortDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    avgRating: 4.8,
  },
];
